djangomarket/ai/urls.py
from django.urls import path, include
from . import views

app_name = 'ai'

urlpatterns = [
    path('inference/new/', views.ai_new, name = "ai_new"),
    path('inference/', views.ai_list, name = "ai_list"),

    path('inference/detail/new/', views.aidetail_new, name = "aidetail_new"),
    path('inference/detail/', views.aidetail_list, name = "aidetail_list"),
    
    # detail view
    path('inference/detail/<int:pk>/', views.aidetail_detail, name = "aidetail_detail"),
]

djangomarket/djangomarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

# DRF and Swagger 관련
from rest_framework.permissions import AllowAny
from drf_yasg.views import get_schema_view 
from drf_yasg import openapi

"""
from django.conf import global_settings
from . import settings
"""
# 이렇게 해야 위 두개를 합쳐서 해준다
from django.conf import settings

from django.conf.urls.static import static
# View관련
# CBV
from django.views.generic import TemplateView, RedirectView

class RootView(TemplateView):
    template_name = 'root.html'


# Swagger로 보고 싶은 urls 추가
schema_url_patterns = [ 
    path('api/', include('drf.urls')),
    ]

schema_view_v1 = get_schema_view(
    openapi.Info(
        title="Open API",
        default_version='v1',
        description="시스템 API",
        terms_of_service="https://www.google.com/policies/terms/",
    ),
    public=True,
    permission_classes=(AllowAny,),
    patterns=schema_url_patterns,
)


# URL pattern 추가
urlpatterns = [
    # path('', RootView.as_view(template_name = "root.html"), name ='root'),
    # 리다이렉트 url = 원하는 이동경로
    path('', RedirectView.as_view(
        # url = '/instagram/'
        pattern_name = "instagram:post_list", #URL Reverse        
        ), name = 'root'), 
    path('admin/', admin.site.urls),

    # DRF
    path('api-auth/', include('rest_framework.urls')),

    # my app
    path('blog1/', include('blog1.urls')), 
    path('instagram/', include('instagram.urls')), 
    path('market/', include('market.urls')), 
    path('accounts/', include('accounts.urls')),
    path('ai/', include('ai.urls')), # for ai inference
    
    # DRF
    path('api/', include('drf.urls')), # drf
    
    # swagger
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view_v1.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view_v1.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view_v1.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]


if settings.DEBUG: #디버그 옵션 참일때만 수행, 즉 디버깅 모드에서만 접근 가능
    # MEDIA_URL로 이미지 접근 가능하게 함!
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

djangomarket/instagram/urls.py
from django.urls import path, include
from . import views

#URL Reverse에서 namespace역할
app_name = 'instagram' 


urlpatterns = [
    # URL reverse : name인자에 url리버스를 수행할 이름을 넘겨주면된다!

    # create view
    # path('ai/inference/new/', views.ai_new, name = "ai_new"),
    path('new/', views.post_new, name = "post_new"),
    
    # list view
    # path('ai/inference/', views.ai_list, name = "ai_list"),
    path('', views.post_list, name = "post_list"),

    # detail view
    path('<int:pk>/', views.post_detail, name = "post_detail"),
    
    # edit view
    path('<int:pk>/edit/', views.post_edit, name = "post_edit"),

]

djangomarket/instagram/models.py
from django.db import models

# settings 불러 올때 이렇게 할것 이래야 우리가 정의한 settings를 오버라이드 함
from django.conf import settings

#TODO: 다시 볼것
from django.urls import reverse

# validator
from django.core.validators import MinLengthValidator

# cache관련
from django.core.cache import cache
# Create your models here.
# for AI
# class AI(models.Model):
#     # upload to : settings.MEDIA_URL/instagram/post/%Y/%m/%d/ 폴더에 쌓임
#     # 누가 추론했는지
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     # 디비에는 파일이 저장된 경로가 들어감
#     # TODO: 사진 저장 경로바꿀것
#     photo = models.ImageField(blank= True, upload_to='ai/post/%Y/%m/%d') ## pillow 라이브러리가 설치되어야 있어야 함!
#     created_at= models.DateTimeField(auto_now_add =True)
#     updated_at = models.DateTimeField(auto_now =True)
#     result_url = models.TextField()
    
#     # URL reverse
#     def get_absolute_url(self):
#         return reverse("instagram:ai_list")

#     # qs 정렬 조건
#     class Meta:
#         ordering = ['-id']
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField(validators=[MinLengthValidator(10)]) #최소 10글자 유효성 검사 로직
    #message = models.TextField(validators=[MinLengthValidator(10)]) #최소 10글자 유효성 검사 로직
    
    # tag set
    # many to many 에서는 blank = True로 두는게 편함
    # 이유 : 포스팅에 태그를 작성 안할수도 있으므로..!
    tag_set= models.ManyToManyField('Tag', blank = True)
    # upload to : settings.MEDIA_URL/instagram/post/%Y/%m/%d/ 폴더에 쌓임
    # 디비에는 파일이 저장된 경로가 들어감
    photo = models.ImageField(blank= True, upload_to='instagram/post/%Y/%m/%d') ## pillow 라이브러리가 설치되어야 있어야 함!
    is_public = models.BooleanField(default=False, verbose_name="공개여부")
    created_at= models.DateTimeField(auto_now_add =True)
    updated_at = models.DateTimeField(auto_now =True)

    # admin의 제목 바꾸고 싶을때
    def __str__(self):
        # return f"Custom Post object create_at {self.created_at}"
        return self.message
    # user defined 함수 지정할 수 있음, 단 인자 없어야 함!
    # def message_length(self):
    #     return len(self.message)
    # message_length.short_description = "메세지 글자수" # 노출될 필드명

    ''' URL Reverse 구현 꼭 모델에 구현해 놓아야 함!!'''
    def get_absolute_url(self):
        return reverse("instagram:post_detail", args= [self.pk])
    
    # 캐싱 관련
    def save(self, *args, **kwargs):
        cache.delete('post_list')
        # print("save함수 호출")
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        cache.delete('post_list')
        # print("delete 함수 호출")
        super().delete(*args, **kwargs)
    
    # qs 정렬 조건
    class Meta:
        ordering = ['-id']

class Comment(models.Model):
    post = models.ForeignKey('instagram.Post', on_delete=models.CASCADE,
                             # 댓글을 쓸 수 있는 posting 항목 제한
                             # Post 모델의 is_public 이 True인 것만 댓글을 달 수 있도록 하겠다!
                             limit_choices_to={'is_pulic' : True}) # 실제 db에는 post_id 필드가 생성됨
    message = models.TextField()
    created_at= models.DateTimeField(auto_now_add =True)
    updated_at = models.DateTimeField(auto_now =True)

    class Meta:
        ordering = ['-id']

#
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    # post_set = 

     # admin의 제목 바꾸고 싶을때
    def __str__(self):
        return self.name

djangomarket/instagram/forms.py
from django import forms
from .models import Post
# from .models import AI
# 정규표현식
import re

# model명과 form 명을
# naming rule : {model명} + Form

'''
 Model Form 사용법
 1. class Meta 에 상속받을 모델명 기입
    model = {상속받을 모델}
    fields = ['원하는 필드명'] or '__all__'
'''
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        # 유효성 검사를 수행할 필드들
        fields= ['message', 'photo', 'tag_set', 'is_public']

    # 개별 필드에 대한 유효성 검사 로직 추가
    '''
    함수명 : clean_{필드명}
    '''
    def clean_message(self):
        message = self.cleaned_data.get('message')
        if message:
            message = re.sub(r'[a-zA-Z]+', '', message) #영어가 있으면 없애버린다
        return message

# class AIForm(forms.ModelForm):
#     class Meta:
#         model = AI
#         fields = ['user','photo']
        

djangomarket/instagram/views.py
# Http Request, Response 관련
from django.http	import HttpRequest,	HttpResponse, Http404

# Models
from .models import Post
from django.contrib.auth import get_user_model
from django.db import models
# from .models import AI
# Forms
from .forms import PostForm
# from .forms import AIForm

# render
from django.shortcuts import render, redirect, get_object_or_404
# 다른 웹서버에 자료 요청용
import requests

# CBV
from django.views.generic import ListView, DetailView
# import requests

# decorator
from django.contrib.auth.decorators	import login_required
# CBV에 입힐 데코레이터
from django.utils.decorators	import method_decorator
# 로그인 인증 관련
from django.contrib.auth.mixins import LoginRequiredMixin

# message framework : 사용자에게 메세지 보여줄때 슴
from django.contrib import messages

# Caching
from django.core.cache import cache
from django.views.decorators.cache import cache_page
# from django.utils.decorators import method_decorator

# Create your views here.
# def ai_new(request):

#     if request.method =="POST":
#         '''
#         author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#         # upload to : settings.MEDIA_URL/instagram/post/%Y/%m/%d/ 폴더에 쌓임
#         # 디비에는 파일이 저장된 경로가 들어감
#         photo = models.ImageField(blank= True, upload_to='instagram/post/%Y/%m/%d') ## pillow 라이브러리가 설치되어야 있어야 함!
#         created_at= models.DateTimeField(auto_now_add =True)
#         updated_at = models.DateTimeField(auto_now =True)
#         result_url = models.TextField()
#         '''
#          #외부 url 요청 처리하는 로직
#         # user모델 받아온다
        
#         form = AIForm(request.POST, request.FILES)

        
#         # print(form)
#         # # print(request.data)
#         if form.is_valid(): #유효성 검사 로직 수행

#             User = get_user_model()
#             current_user = User.objects.filter(pk=request.POST['user'])
#             # print('user', current_user)

#             files = request.FILES['photo']
#             upload = {'image': files}

#             # res = requests.post(' http://127.0.0.1:5000/image/', files = upload)
#             url = 'http://192.168.1.141:8000/inference/'
#             res = requests.post(url, files = upload)
#             # print(res.json())
#             # 모델 인스턴스 생성
#             # print(request.POST)
#             temp = AI(user = current_user.first() , photo = request.FILES['photo'], result_url = res.json()['result_image_url'] )
#             # print(temp)
#             # 모델결과 저장
#             temp.save()
            
#             # TODO: 요청결과 테이블로 볼 수 있도록 생성
#             # return redirect('/instagram/ai/inference/')

#             # url reverse
#             return redirect(temp)
        
#     else: #request.method == "GET"일경우 
#         # 빈 폼 반환
#         form = AIForm()
#     # print(form)
    
#     return render(request, 'instagram/ai_form.html', {
#         'form' : form,
#     })

@login_required
def post_new(request):

    if request.method =="POST":
        form = PostForm(request.POST, request.FILES)
        
        if form.is_valid(): #유효성 검사 로직 수행

            # 1. 데이터 접근
            '''
            request.POST['message'로 접근하면 안됨] --> 유효성 검사 통과한 데이터들만 받아야 하므로
            따라서, form.cleaned_data 로 꼭 접근해야 함!
            '''
            
            # message = form.cleaned_data['message']
            # print('message', message)
            
            # 2. 데이터 저장
            post = form.save(commit= False) #유저정보 안넘어왔으므로 따로 저장해줘야함
            post.author = request.user 
            #현재 로그인 유저 인스턴스 --> 로그인 상황임을 보장 받아야 함 , @login_required 장식자로 감싸야 함
            # DB에 저장
            post.save()

            # 3. success url 이동
            # redirect 
            return redirect(post)
        
    else: #request.method == "GET"일경우 
        # 빈 폼 반환
        form = PostForm()
    
    return render(request, 'instagram/post_form.html', {
        'form' : form,
    })
    
'''
form 내용 : 테이블 html 태그이므로, <table></table>로 감싸야 한다!

<tr><th><label for="id_message">Message:</label></th><td><textarea name="message" cols="40" rows="10" required id="id_message">
</textarea></td></tr>
<tr><th><label for="id_photo">Photo:</label></th><td><input type="file" name="photo" accept="image/*" id="id_photo"></td></tr>
<tr><th><label for="id_is_public">공개여부:</label></th><td><input type="checkbox" name="is_public" id="id_is_public"></td></tr>
'''


# CBV
# 기본
# post_list = ListView.as_view(model = Post, paginate_by =10)
'''
method decorator
첫번째 인자 : decorator 종류 : 어떤 데코레이터로 입히고 싶은지
name : 어떤 멤버함수에 첫번째 인자로 지정한 decorator를 입히고 싶은지
'''

# 방법 1
# @method_decorator(login_required, name = 'dispatch')
# class PostListView(ListView):
#     model= Post
#     paginate_by = 10

# 방법 2

class PostListView(LoginRequiredMixin, ListView):
    model= Post
    paginate_by = 10
    
    @method_decorator(cache_page(60, cache='default'))  # 60초 동안 캐시 유지
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    # FIXME: mongodb에서 잘 안됨, RDBMS에서는 잘됨
    def get_queryset(self):
        search_query = self.request.GET.get('q')
        queryset = super().get_queryset()

        if search_query:
            queryset = queryset.filter(
                models.Q(author__username__icontains=search_query) |
                models.Q(message__icontains=search_query) |
                models.Q(tag_set__name__icontains=search_query)
            ).distinct()

        return queryset
    # Redis caching
    # def get_queryset(self):
    #     search_query = self.request.GET.get('q')

    #     if search_query:
    #         cache_key = f'post_search:{search_query}'
    #         cached_queryset = cache.get(cache_key)
            

    #         if cached_queryset is None:
    #             queryset = super().get_queryset().filter(
    #                 models.Q(author__username__icontains=search_query) |
    #                 models.Q(message__icontains=search_query) |
    #                 models.Q(tag_set__name__icontains=search_query)
    #             ).distinct()

    #             # 결과를 캐시에 저장
    #             cache.set(cache_key, queryset)
    #         else:
    #             queryset = cached_queryset
    #     else:
    #         cache_key = 'post_list'
    #         cached_queryset = cache.get(cache_key)
    #         # print("cached_queryset", cached_queryset    )

    #         if cached_queryset is None:
    #             queryset = super().get_queryset()
    #             # posts = list(super().get_queryset())
    #         # cache.set('post_list', posts)
    #             # 결과를 캐시에 저장
    #             cache.set(cache_key, queryset)
    #         else:
    #             queryset = cached_queryset

    #     return queryset

post_list = PostListView.as_view()


# FBV
# @login_required
# def post_list(request):
#     qs = Post.objects.all()
#     print(request.GET)
#     q = request.GET.get('q', '')
#     if q:
#         qs = qs.filter(message__icontains = q)
#     # instagram/templates/instagram/post_list.html
#     return render(request, 'instagram/post_list.html', {
#         'post_list' : qs,
#         'q' : q,
#     })

# def post_detail(request, pk):
#     response = HttpResponse()
#     response.write("Hello World!")
#     return response


# CBV

'''
기본버전
DetailView에는 따로 안넘겨도 query string이 catpure되어 넘겨진다

path('<int:pk>/', views.post_detail),
여기서 pk가 인자로 알아서 넘어가서 queryset을 형성한다

'''
# 기본버전
'''
post_detail = DetailView.as_view(model = Post)

'''

# is_public = True인것만 볼 수 있게
'''
post_detail = DetailView.as_view(
    model = Post,
    queryset= Post.objects.filter(is_public =True)
)
'''

class PostDetailView(DetailView):
    model = Post
    # queryset = Post.objects.filter(is_pubic = True)
    
    # DetailView를 상속받아 재정의
    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_authenticated:  # 현재 로그인 한 유저의 인스턴스
            qs = qs.filter(is_public = True) # 로그인 안한 유저들은 is_public = True만 볼 수 있도록
        return qs
post_detail = PostDetailView.as_view()

# FBV
# def post_detail(request, pk): # 두번째 인자 이름은 urls.py의 path('<int:pk>/', views.post_detail), 의 capture 된 문자열과 정확하게 일치해야 한다!
#     # try:
#     #     post = Post.objects.get(pk = pk)
#     # except:
#     #     raise Http404

#     # 위와 같은 로직
#     post = get_object_or_404(Post, pk = pk)

#     return render(request, 'instagram/post_detail.html', {
#         'post' : post,
#     })


    

# def ai_list(request):
#     # print(request.GET)
#     q = request.GET.get('q', '')
#     if q:
#         User = get_user_model()
#         current_user = User.objects.filter(username=q).first()
#         qs = current_user.ai_set.all()
#         print(qs)
#     # instagram/templates/instagram/post_list.html
#     else:
#         qs = AI.objects.all()
        
#     return render(request, 'instagram/ai_list.html', {
#         'ai_list' : qs,
#         'q' : q,
#     })


# edit view
@login_required
def post_edit(request, pk):
    # 일단 pk에 해당하는 모델에 대한 정보를 얻어온다
    post = get_object_or_404(Post, pk= pk) #모델 인스턴스 넘어온다

    # 작성자가 아닌 다른 사람이 게시물에 접근할 경우
    if post.author != request.user:
        # 메세지 보여줌
        messages.error(request, '작성자만 수정할 수 있습니다')
        return redirect(post)
    
    if request.method =="POST":
        
        form = PostForm(request.POST, request.FILES, instance=post)
        
        # reqeust로 넘어오는 것들 확인
        print("request.POST, request.FILES, request.method, request.user", request.POST, request.FILES, request.method, request.user)
        print("------------------------------------------")
        # print("request.data", request.data)
        if form.is_valid(): #유효성 검사 로직 수행
            
            # 유호성 검사 통과한 데이터들 DB저장
            post = form.save()

            # redirect 
            # post에 해당하는 모델에 구현된 get_abolute_url로 리다이렉트 됨
            return redirect(post)
        
    else: #request.method == "GET"일경우 
        # 빈 폼 반환
        form = PostForm(instance=post)
    # print(form)
    
    return render(request, 'instagram/post_form.html', {

djangomarket/instagram/templates/instagram/ai_list.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<body>

    <form action = "" method = "get">
        <input type = "text" name = "q" , value = "{{q}}"/>
        <input type = "submit" value = "검색" />
    </form>
    {% comment %} url reverse {% endcomment %}
    <a href = {% url "instagram:ai_new" %} class = 'btn btn-primary'>새 추론</a>
    <table class = "table table-bordered table-hover">
        <tbody>
            <tr>
                <td>
                    user
                </td>
                <td>
                    입력자료
                </td>
                
                <td>
                    추론결과
                </td>
            </tr>
        {% for elem in ai_list %}
            
            <tr>
                <td>
                    {{elem.user.username}}
                </td>
                <td>
                    {% if elem.photo %}
                        <img src = {{elem.photo.url}} style = "width:200px"/>
                    {% else %}
                        No photo
                    {% endif %}
                </td>
                <td>
                    <img src = {{elem.result_url}} style = "width:200px"/>
                </td>
                
                
            </tr>
        {% endfor %}
        </tbody>
        </table>
</body>

djangomarket/instagram/templates/instagram/layout.html
{% comment %} UI관련 라이브러리 임포트 {% endcomment %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <title>
        {% block title %}
        {% endblock title%}
    </title>
    <!-- css, js import -->
    
    <!-- 다양한 테마 가능 -->
    <!-- 주소 : https://www.bootstrapcdn.com/bootswatch/ -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/darkly/bootstrap.min.css" integrity="sha384-nNK9n28pDUDDgIiIqZ/MiyO3F4/9vsMtReZK39klb/MtkZI3/LtjSjlmyVPS3KdN" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <!-- Note : bootstrap4는 내부적으로 jquery를 이용하므로, 받아놔야 한다 -->
    <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <style>
        /* 반응형 --> 600px 아래로 가면 바디태그 background color green으로 변경 */
        /* @media (max-width: 600px) {
            body {
                background-color: green;
            } 
        } */
        body {
            padding-top: 5rem;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false">Dropdown</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    <div class ="contianer">
        <div class = "row">
            <div class = "col-sm-12">
                {% block content %}
                {% endblock content%}
                </hr>
                &copy; PPARK AI platform
            </div>
            
            
        </div> 


    </div>

    
        
</body>

</html>

djangomarket/instagram/templates/instagram/post_detail.html
{% extends "instagram/layout.html" %}
{% block title%}
    Post detail
{% endblock title%}

{% block content %}
<h2>
    Author : {{post.author}}
</h2>
{%if post.photo%}
    <img src = "{{post.photo.url}}" style = "width: 100px;" />
{% endif %}
<div>
    {{post.message}}
</div>
</hr>

{% comment %} url reverse {% endcomment %}
<a href="{% url 'instagram:post_list' %}" class ="btn btn-primary">
    목록
</a>
<a href="{% url 'instagram:post_edit' post.pk %}" class ="btn btn-info">
    수정
</a>

{% endblock content %}

djangomarket/instagram/templates/instagram/post_form.html
{% comment %} <form action "http://192.168.1.141:8000/inference/" method = "post" enctype = "multipart/form-data"> {% endcomment %}
<form action "" method = "post" enctype = "multipart/form-data">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <input type = "submit" value= "저장"/>
</form>

djangomarket/instagram/templates/instagram/post_list.html
{% extends "instagram/layout.html" %} 
{% comment %} 부모 레이아웃 상속 {% endcomment %}
{% comment %} UI관련 라이브러리 임포트 {% endcomment %}
{% load bootstrap4 %} 


{% block title %}
Post list
{% endblock title %}

{% block content %}
<form action = "" method = "get">
    <input type = "text" name = "q" , value = "{{q}}"/>
    <input type = "submit" value = "검색" />
</form>
<a href = "./new/" class = 'btn btn-primary'>새 포스팅</a>
<table class = "table table-bordered table-hover">
    <tbody>
        <tr>
            <td>
                pk
            </td>
            <td>
                user
            </td>
            <td>
                photo
            </td>
            <td>
                message
            </td>
            <td>
                created_at
            </td>
            <td>
                tag
            </td>
        </tr>
    {% for post in post_list %}
        
        <tr>
            <td>
                {{post.pk}}
            </td>
            <td>
                {{post.author.username}}
            </td>
            <td>
                {% if post.photo %}
                    <img src = {{post.photo.url}} style = "width:70px"/>
                {% else %}
                    No photo
                {% endif %}
            </td>
            <td>
                {% comment %} url reverse 동작하도록 .. {% endcomment %}
                {% comment %} <a href="{% url "instagram:post_detail" post.pk %}"> {% endcomment %}
                <a href="{{post.get_absolute_url}}">
                    {{post.message}}
                </a>
            
            </td>
            <td>
            {{post.created_at}}
            </td>
            <td>
                {% comment %} represent many to many field {% endcomment %}
                {% for tag in post.tag_set.all%}
                    {{tag}}
                {% endfor %}
            </td>
            
        </tr>
    {% endfor %}
    </tbody>
    </table>

    <!-- 페이징 처리 -->
    {% comment %} {{is_paginated}}
    {{page_obj}} {% endcomment %}
    
    {% comment %} 페이징 처리 : bootstrap4 라이브러리 활용 
    띄어쓰기 민감하므로 없이 처리!!
    {% endcomment %}
    {% if is_paginated %}
        {% bootstrap_pagination page_obj size="small" justify_content="center"%}
    {% endif %}
{% endblock content %}