djangomarket/ai/urls.py
from django.urls import path, include
from . import views

app_name = 'ai'

urlpatterns = [
    path('inference/new/', views.ai_new, name = "ai_new"),
    path('inference/', views.ai_list, name = "ai_list"),

    path('inference/detail/new/', views.aidetail_new, name = "aidetail_new"),
    path('inference/detail/', views.aidetail_list, name = "aidetail_list"),
    
    # detail view
    path('inference/detail/<int:pk>/', views.aidetail_detail, name = "aidetail_detail"),
]

djangomarket/djangomarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

# DRF and Swagger 관련
from rest_framework.permissions import AllowAny
from drf_yasg.views import get_schema_view 
from drf_yasg import openapi

"""
from django.conf import global_settings
from . import settings
"""
# 이렇게 해야 위 두개를 합쳐서 해준다
from django.conf import settings

from django.conf.urls.static import static
# View관련
# CBV
from django.views.generic import TemplateView, RedirectView

class RootView(TemplateView):
    template_name = 'root.html'


# Swagger로 보고 싶은 urls 추가
schema_url_patterns = [ 
    path('api/', include('drf.urls')),
    ]

schema_view_v1 = get_schema_view(
    openapi.Info(
        title="Open API",
        default_version='v1',
        description="시스템 API",
        terms_of_service="https://www.google.com/policies/terms/",
    ),
    public=True,
    permission_classes=(AllowAny,),
    patterns=schema_url_patterns,
)


# URL pattern 추가
urlpatterns = [
    # path('', RootView.as_view(template_name = "root.html"), name ='root'),
    # 리다이렉트 url = 원하는 이동경로
    path('', RedirectView.as_view(
        # url = '/instagram/'
        pattern_name = "instagram:post_list", #URL Reverse        
        ), name = 'root'), 
    path('admin/', admin.site.urls),

    # DRF
    path('api-auth/', include('rest_framework.urls')),

    # my app
    path('blog1/', include('blog1.urls')), 
    path('instagram/', include('instagram.urls')), 
    path('market/', include('market.urls')), 
    path('accounts/', include('accounts.urls')),
    path('ai/', include('ai.urls')), # for ai inference
    
    # DRF
    path('api/', include('drf.urls')), # drf
    
    # swagger
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view_v1.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view_v1.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view_v1.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]


if settings.DEBUG: #디버그 옵션 참일때만 수행, 즉 디버깅 모드에서만 접근 가능
    # MEDIA_URL로 이미지 접근 가능하게 함!
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

djangomarket/ai/models.py
from django.db import models

# settings 불러 올때 이렇게 할것 이래야 우리가 정의한 settings를 오버라이드 함
from django.conf import settings

#TODO: 다시 볼것
from django.urls import reverse

# validator
from django.core.validators import MinLengthValidator


# Create your models here.
# for AI

# 그냥 기본모델로 추론 할 때 쓰임
class AI(models.Model):
    # upload to : settings.MEDIA_URL/instagram/post/%Y/%m/%d/ 폴더에 쌓임
    # 누가 추론했는지

    '''
    related name : {appname}_{modelname}_set
    ''' 
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="ai_ai_set")
    # 디비에는 파일이 저장된 경로가 들어감
    # TODO: 사진 저장 경로바꿀것
    photo = models.ImageField(blank= True, upload_to='ai/post/%Y/%m/%d') ## pillow 라이브러리가 설치되어야 있어야 함!
    created_at= models.DateTimeField(auto_now_add =True)
    updated_at = models.DateTimeField(auto_now =True)
    # result_url = models.TextField()
    result = models.JSONField()

    # URL reverse
    '''
    redirect(모델) 시 호출되는 주소
    '''
    def get_absolute_url(self):
        return reverse("ai:aidetail_detail", args= [self.pk])
    # def get_absolute_url(self):
    #     return reverse("ai:ai_list")

    # qs 정렬 조건
    class Meta:
        ordering = ['-id']

class AIDetail(models.Model):
    # upload to : settings.MEDIA_URL/instagram/post/%Y/%m/%d/ 폴더에 쌓임

    '''
    related name : {appname}_{modelname}_set
    ''' 
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="ai_aidetail_set")
    
    # 어떤 카테고리 작업을 할건지.. 1개 카테고리에 N개 Post이 존재할 수 있으므로..
    task_category = models.ForeignKey('ai.Task', on_delete=models.CASCADE, related_name="ai_aidetail_set")

    # 어떤 모델을 사용할 것인지
    # model_name = models.ForeignKey('ai.InferenceModel', on_delete=models.CASCADE)

    # 디비에는 파일이 저장된 경로가 들어감
    photo = models.ImageField(blank= True, upload_to='ai/detail//%Y/%m/%d') ## pillow 라이브러리가 설치되어야 있어야 함!
    created_at= models.DateTimeField(auto_now_add =True)
    updated_at = models.DateTimeField(auto_now =True)
    
    # 추론결과 넘어오는 필드
    result = models.JSONField() ##TODO: 결과들 분리
    
    # URL reverse
    def get_absolute_url(self):
        return reverse("ai:aidetail_detail", args= [self.pk])
    # qs 정렬 조건
    class Meta:
        ordering = ['-id']


class Task(models.Model):
    # Task 이름
    name = models.TextField()
    def __str__(self):
        # return f"Custom Post object create_at {self.created_at}"
        return self.name
    
    
class InferenceModel(models.Model):
    
    #TODO: 테이블 설계 바꾸기
    # task = models.ForeignKey('ai.Task', on_delete=models.CASCADE)

    # 모델 명
    task = models.ForeignKey('ai.Task', on_delete=models.CASCADE )
    name = models.TextField()
    def __str__(self):
        # return f"Custom Post object create_at {self.created_at}"
        return self.name

djangomarket/ai/forms.py
from django import forms
from .models import AI, AIDetail, InferenceModel, Task

# model명과 form 명을
# naming rule : {model명} + Form

'''
 Model Form 사용법
 1. class Meta 에 상속받을 모델명 기입
    model = {상속받을 모델}
    fields = ['원하는 필드명'] or '__all__'
'''

class AIForm(forms.ModelForm):
    class Meta:
        model = AI
        fields = ['user','photo']
        

# 기본 하나의 모델에 있는 필드만 표출하고 싶을 경우
# class AIDetailForm(forms.ModelForm):
#     class Meta:
#         model = AIDetail
#         fields = ['user','photo', 'task_category', 'model_name']


# 외부 모델 필드 참조하고 싶을때
class AIDetailForm(forms.ModelForm):

    # 다른 모델 참조해서 필드에 넣고 싶을때
    inference_model_name = forms.ModelChoiceField(
        queryset=InferenceModel.objects.all(),
        label='Inference Model Name'
    )

    # test
    # task = forms.ModelChoiceField(
    #     queryset=Task.objects.all(),
    #     label='task'
    # )

    class Meta:
        model = AIDetail
        fields = ['photo', 'task_category', 'inference_model_name']
        # fields = ['user', 'photo', 'task_category', 'task']




# class AIDetailForm(forms.ModelForm):
#     def __init__(self, *args, **kwargs):
#         task_category = kwargs.pop('task_category', None)
#         super(AIDetailForm, self).__init__(*args, **kwargs)
#         if task_category:
#             self.fields['inference_model_name'].queryset = InferenceModel.objects.filter(task=task_category)

#     inference_model_name = forms.ModelChoiceField(
#         queryset=InferenceModel.objects.none(),
#         label='Inference Model Name'
#     )

#     class Meta:
#         model = AIDetail
#         fields = ['user', 'photo', 'task_category', 'inference_model_name']

djangomarket/ai/views.py
# Http Request, Response 관련
from django.http	import HttpRequest,	HttpResponse, Http404

# Models
from .models import  AI, AIDetail, Task
from django.db import models
from django.contrib.auth import get_user_model

# Forms
from .forms import AIForm, AIDetailForm

# render
from django.shortcuts import render, redirect, get_object_or_404
# 다른 웹서버에 자료 요청용
import requests

# CBV
from django.views.generic import ListView, DetailView
# import requests

# decorator
from django.contrib.auth.decorators	import login_required
# CBV에 입힐 데코레이터
from django.utils.decorators	import method_decorator
# 로그인 인증 관련
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.



def ai_new(request):
    if request.method =="POST":
        # 폼 생성
        form = AIForm(request.POST, request.FILES)

        # print(form)
        # # print(request.data)
        if form.is_valid(): #유효성 검사 로직 수행

            User = get_user_model()
            current_user = User.objects.filter(pk=request.POST['user'])
            # print('user', current_user)

            files = request.FILES['photo']
            upload = {'image': files}

            # res = requests.post(' http://127.0.0.1:5000/image/', files = upload)
            url = 'http://192.168.1.141:8000/inference/'
            res = requests.post(url, files = upload) # 요청한 결과 res에 받음
            # print(res.json())
            # 모델 인스턴스 생성
            # print(request.POST)
            # temp = AI(user = current_user.first() , photo = request.FILES['photo'], result_url = res.json()['result_image_url'] )
            
            temp = AI(user = current_user.first() , photo = request.FILES['photo'], result = res.json())
            # print(temp)
            # 모델결과 저장
            temp.save()
            
            # TODO: 요청결과 테이블로 볼 수 있도록 생성
            # return redirect('/instagram/ai/inference/')

            # url reverse
            return redirect(temp)
        
    else: #request.method == "GET"일경우 
        # 빈 폼 반환
        form = AIForm()
    # print(form)
    
    return render(request, 'ai/ai_form.html', {
        'form' : form,
    })

def aidetail_new(request):
    if request.method =="POST":
         
        form = AIDetailForm(request.POST, request.FILES)

        # print(form)
        # # print(request.data)
        if form.is_valid(): #유효성 검사 로직 수행
            # user모델 받아온다
            # User = get_user_model()
            # current_user = User.objects.filter(pk=request.POST['user'])
            # print('user', current_user)


            # 1. 외부 url 요청(AI 서버로)
            files = request.FILES['photo']
            upload = {'image': files}

            # res = requests.post(' http://127.0.0.1:5000/image/', files = upload)
            url = 'http://192.168.1.141:8000/inference/'
            res = requests.post(url, files = upload) # 요청한 결과 res에 받음
            # print(res.json())
            # 모델 인스턴스 생성
            # print(request.POST)
             
            # 2. form save
            '''
            form.save() 하면 내부적으로 model instance를 반환해줌
            form.save()에는 내부적으로 유효성 검사 통과한 clean_data가 넘어감
            ''' 
            aidetail = form.save(commit=False) #commit False로 해야 추가적인 정보를 저장할 수 있음
            # print("aidetail", aidetail)
            # 3. 데이터 추가
            '''
            API 요청해서 받은 결과를 모델인스턴스에 추가함
            '''
            aidetail.result = res.json()
            aidetail.user = request.user # 유저정보 입력
            aidetail.save() #이래야 최종적으로 DB에 저장됨

            # 4. go success url 
            return redirect(aidetail) # url reverse
            # return redirect('http://127.0.0.1:8000/ai/inference/detail/')
    else: #request.method == "GET"일경우 
        # 빈 폼 반환
        form = AIDetailForm()

        # form = AIDetailForm(task_category=my_task_category)
    # print(form)
    
    return render(request, 'ai/aidetail_form.html', {
        'form' : form,
    })

# 기존 코드
# def ai_list(request):
#     # print(request.GET)
    
#     q = request.GET.get('q', '')
#     if q:
#         User = get_user_model()

#         # 쿼리스트링으로 넘어온 유저로 검색
#         current_user = get_object_or_404(User, username=q)
#         # current_user = User.objects.filter(username=q).first()
        
#         # 유저에 해당되는 모든 ai 결과들 쿼리
#         qs = current_user.ai_ai_set.all()
#         print(qs)
#     # instagram/templates/instagram/post_list.html
#     else:
#         # 쿼리스트링으로 아무것도 안들어올 시 그냥 모두 검색
#         qs = AI.objects.all()
        
#     return render(request, 'ai/ai_list.html', {
#         'ai_list' : qs,
#         'q' : q,
#     })


# 개선코드
@login_required #로그인 필수
def ai_list(request):
    # GET 인자로 넘어온 것 확인
    # print(request.GET)
    
    # 로그인된 유저 확인
    # print('로그인된 유저', request.user )

    # 검색 기능 구현
    # 사용모델로 검색
    q = request.GET.get('q', '')
    if q:
        User = get_user_model()

        # 쿼리스트링으로 넘어온 유저로 검색
        current_user = get_object_or_404(User, username=q)
        # current_user = User.objects.filter(username=q).first()
        
        # 유저에 해당되는 모든 ai 결과들 쿼리
        qs = current_user.ai_ai_set.all()
        print(qs)
    # instagram/templates/instagram/post_list.html
    else:
        # 쿼리스트링으로 아무것도 안들어올 시 유저이름으로 그냥 모두 검색
        qs = AI.objects.filter(user = request.user)
        
    return render(request, 'ai/ai_list.html', {
        'ai_list' : qs,
        'q' : q,
    })

@login_required
def aidetail_list(request):
    # print(request.GET)

    q = request.GET.get('q')
    
    #FIXME: 다른 필드 넣어서 확인
    # if q:
    #     qs = AIDetail.objects.all()
    #     qs = qs.filter(
    #         models.Q(task_category__icontains=q) |
    #         models.Q(user__icontains=q)
    #     )

    if q:
        User = get_user_model()

        # 쿼리스트링으로 넘어온 유저로 검색
        current_user = get_object_or_404(User, username=q)
        # current_user = User.objects.filter(username=q).first()
        
        # 유저에 해당되는 모든 ai 결과들 쿼리
        qs = current_user.ai_aidetail_set.all()
        # print(qs)
    # instagram/templates/instagram/post_list.html
    else:
        # 쿼리스트링으로 아무것도 안들어올 시 그냥 모두 검색
        qs = AIDetail.objects.all()
        
    return render(request, 'ai/aidetail_list.html', {
        'aidetail_list' : qs,
        'q' : q,
    })


# @login_required
# def aidetail_list(request):
#     # print(request.GET)

#     # 추론한 모델 태스크로 검색
#     q = request.GET.get('q', '')
#     if q:
#         #TODO: 문자열 포함결과로 검색 구현
#         # task = Task.objects.filter(name__icontains = 'In')

#         # 쿼리스트링으로 넘어온 태스크 카테고리로 검색 
#         task = get_object_or_404(Task, name=q)
        
#         # 태스크에 해당되는 모든 ai 결과들 쿼리
#         qs = task.ai_aidetail_set.all()
#         # print(qs)
    
#     # instagram/templates/instagram/post_list.html
#     else:
#         # 쿼리스트링으로 아무것도 안들어올 시 유저가 요청한 추론 내역이 다 보임
#         qs = AIDetail.objects.filter(user = request.user)
        
#     return render(request, 'ai/aidetail_list.html', {
#         'aidetail_list' : qs,
#         'q' : q,
#     })

# --------------------------Detail View ---------------------------#

# @login_required
class AIDetailDetailView(DetailView):
    model = AIDetail
    # queryset = Post.objects.filter(is_pubic = True)
    
    # DetailView를 상속받아 재정의
    # def get_queryset(self):
    #     qs = super().get_queryset()
    #     if not self.request.user.is_authenticated:  # 현재 로그인 한 유저의 인스턴스
    #         qs = qs.filter(is_public = True) # 로그인 안한 유저들은 is_public = True만 볼 수 있도록
    #     return qs

aidetail_detail = AIDetailDetailView.as_view()

djangomarket/ai/templates/ai/ai_form.html
{% extends "instagram/layout.html" %} 
{% comment %} 부모 레이아웃 상속 {% endcomment %}
{% comment %} UI관련 라이브러리 임포트 {% endcomment %}
{% load bootstrap4 %} 


{% block title %}
{% endblock title %}

{% block content %}
<form action "http://192.168.1.141:8000/inference/" method = "post" enctype = "multipart/form-data">
    {% comment %} <form action "" method = "post" enctype = "multipart/form-data"> {% endcomment %}
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <input type = "submit" value= "저장"/>
</form>
{% endblock content %}

djangomarket/ai/templates/ai/ai_list.html
{% extends "instagram/layout.html" %} 
{% comment %} 부모 레이아웃 상속 {% endcomment %}
{% comment %} UI관련 라이브러리 임포트 {% endcomment %}
{% load bootstrap4 %} 


{% block title %}
AI list
{% endblock title %}

{% block content %}
<form action = "" method = "get">
    <input type = "text" name = "q" , value = "{{q}}"/>
    <input type = "submit" value = "검색" />
</form>
{% comment %} url reverse {% endcomment %}
<a href = {% url "ai:ai_new" %} class = 'btn btn-primary'>새 추론</a>
<table class = "table table-bordered table-hover">
    <tbody>
        <tr>
            <td>
                user
            </td>
            <td>
                입력자료
            </td>
            
            <td>
                추론결과
            </td>
        </tr>
    {% for elem in ai_list %}
        
        <tr>
            <td>
                {{elem.user.username}}
            </td>
            <td>
                {% if elem.photo %}
                    <img src = {{elem.photo.url}} style = "width:200px"/>
                {% else %}
                    No photo
                {% endif %}
            </td>
            <td>
                <img src = {{elem.result.result_image_url}} style = "width:200px"/>
            </td>
            
            
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock content %}

djangomarket/ai/templates/ai/ai_list_old.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<body>

    <form action = "" method = "get">
        <input type = "text" name = "q" , value = "{{q}}"/>
        <input type = "submit" value = "검색" />
    </form>
    {% comment %} url reverse {% endcomment %}
    <a href = {% url "ai:ai_new" %} class = 'btn btn-primary'>새 추론</a>
    <table class = "table table-bordered table-hover">
        <tbody>
            <tr>
                <td>
                    user
                </td>
                <td>
                    입력자료
                </td>
                
                <td>
                    추론결과
                </td>
            </tr>
        {% for elem in ai_list %}
            
            <tr>
                <td>
                    {{elem.user.username}}
                </td>
                <td>
                    {% if elem.photo %}
                        <img src = {{elem.photo.url}} style = "width:200px"/>
                    {% else %}
                        No photo
                    {% endif %}
                </td>
                <td>
                    <img src = {{elem.result.result_image_url}} style = "width:200px"/>
                </td>
                
                
            </tr>
        {% endfor %}
        </tbody>
        </table>
</body>

djangomarket/ai/templates/ai/aidetail_detail.html
{% extends "ai/layout.html" %}
{% block title%}
    AI detail
{% endblock title%}

{% block content %}
<h2>
    추론자 : {{aidetail.user}}
</h2>
{% if aidetail.photo %}
    <img src = "{{aidetail.photo.url}}" style = "width: 400px;" />
{% endif %}


<img src = "{{aidetail.result.result_image_url}}" style = "width: 400px;" />
</br>
{% comment %} 
{% for elem in aidetail.result %}
    {{elem}}
{% endfor %}  {% endcomment %}

<div>
    image labels
</div>

<div>
    {{aidetail.result.labels}}
</div>    



{% comment %} url reverse {% endcomment %}
<a href="{% url 'ai:aidetail_list' %}" class ="btn btn-primary">
    목록
</a>
{% comment %} <a href="{% url 'ai:aidetail_edit' post.pk %}" class ="btn btn-info">
    수정
</a> {% endcomment %}

{% endblock content %}

djangomarket/ai/templates/ai/aidetail_form.html
{% extends "instagram/layout.html" %} 
{% comment %} 부모 레이아웃 상속 {% endcomment %}
{% comment %} UI관련 라이브러리 임포트 {% endcomment %}
{% load bootstrap4 %} 

{% block title %}
{% endblock title %}

{% block content %}
<form action "http://192.168.1.141:8000/inference/" method = "post" enctype = "multipart/form-data">
    {% comment %} <form action "" method = "post" enctype = "multipart/form-data"> {% endcomment %}
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <input type = "submit" value= "저장"/>
</form>
{% endblock content %}

djangomarket/ai/templates/ai/aidetail_list.html
{% extends "instagram/layout.html" %} 
{% comment %} 부모 레이아웃 상속 {% endcomment %}
{% comment %} UI관련 라이브러리 임포트 {% endcomment %}
{% load bootstrap4 %} 


{% block title %}
AI Detail
{% endblock title %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<body>

    <form action = "" method = "get">
        <input type = "text" name = "q" , value = "{{q}}"/>
        <input type = "submit" value = "검색" />
    </form>
    {% comment %} url reverse {% endcomment %}
    <a href = {% url "ai:aidetail_new" %} class = 'btn btn-primary'>새 추론</a>
    <table class = "table table-bordered table-hover">
        <tbody>
            <tr>
                <td>
                    user
                </td>
                <td>
                    입력자료
                </td>
                <td>
                    task category
                </td>
                <td>
                    사용 모델
                </td>
                
                <td>
                    추론결과
                </td>
            </tr>
        {% for elem in aidetail_list %}
            
            <tr>
                <td>
                    {{elem.user.username}}
                </td>
                <td>
                    {% if elem.photo %}
                        <img src = {{elem.photo.url}} style = "width:200px"/>
                    {% else %}
                        No photo
                    {% endif %}
                </td>
                <td>
                    {{elem.task_category.name}}
                </td>
                {% comment %} <td>
                    {{elem.model_name.name}}
                </td> {% endcomment %}
                <td>
                    {% for t in elem.task_category.inferencemodel_set.all %}
                    {% comment %} TODO: 유저가 입력한 모델만 보여지게끔 {% endcomment %}
                        {{t.name}}
                    {% endfor %}
                    
                    
                </td>
                <td>
                    <a href="{{elem.get_absolute_url}}">
                        <img src = {{elem.result.result_image_url}} style = "width:200px"/>
                    </a>
                    
                </td>
                
                
            </tr>
        {% endfor %}
        </tbody>
        </table>
</body>

{% endblock content %}

djangomarket/ai/templates/ai/layout.html
{% extends "layout.html"%}